variables:
    DANGER_GITLAB_HOST: git.selfhost.com
    DANGER_GITLAB_API_BASE_URL: https://git.selfhost.com/api/v4
    DANGER_GITLAB_API_TOKEN: C_5_hUKcJWP4kCmTj-UC
stages:
    - danger
danger:
    stage: danger
    image:
        ruby:2.3.1
        name: dantoml/danger:latest
        entrypoint: [""]
    before_script:
        - ruby -v
        - which ruby
        - gem install bundler
        - bundle install
        - danger --version
    script:
        - danger