variables:
    DANGER_GITLAB_HOST: git.selfhost.com
    DANGER_GITLAB_API_BASE_URL: https://git.selfhost.com/api/v4
stages:
    - danger
danger:
    stage: danger
    image:
        name: dantoml/danger:latest
        entrypoint: [""]
    before_script:
        - danger --version
    script:
        - danger