disabled_rules: # rule identifiers to exclude from running
  - force_cast
  - force_unwrappingitespace
  - type_name
  
force_unwrapping: warning

line_length: 510

type_body_length:
  - 300 # warning
  - 400 # error

file_length:
  warning: 500
  error: 1200
  
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
